language: python

# repo_token: bORvIT6qSJYenKryEOXsgfZ6RnQo7r3bw

python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
# command to run tests
script:
  - pytest

after_success:
  - coveralls